language: go

install:
        - go get golang.org/x/lint/golint

script:
        - go test -v ./...
        - go test -cover -race ./...
        - go vet ./...
        - test -z "$(find . -name \*.go | xargs gofmt -d -s)"
        - golint ./...

sudo: false
